require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe JobPropertiesController do

  # This should return the minimal set of attributes required to create a valid
  # JobProperty. As you add validations to JobProperty, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all job_properties as @job_properties" do
      job_property = JobProperty.create! valid_attributes
      get :index
      assigns(:job_properties).should eq([job_property])
    end
  end

  describe "GET show" do
    it "assigns the requested job_property as @job_property" do
      job_property = JobProperty.create! valid_attributes
      get :show, :id => job_property.id.to_s
      assigns(:job_property).should eq(job_property)
    end
  end

  describe "GET new" do
    it "assigns a new job_property as @job_property" do
      get :new
      assigns(:job_property).should be_a_new(JobProperty)
    end
  end

  describe "GET edit" do
    it "assigns the requested job_property as @job_property" do
      job_property = JobProperty.create! valid_attributes
      get :edit, :id => job_property.id.to_s
      assigns(:job_property).should eq(job_property)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new JobProperty" do
        expect {
          post :create, :job_property => valid_attributes
        }.to change(JobProperty, :count).by(1)
      end

      it "assigns a newly created job_property as @job_property" do
        post :create, :job_property => valid_attributes
        assigns(:job_property).should be_a(JobProperty)
        assigns(:job_property).should be_persisted
      end

      it "redirects to the created job_property" do
        post :create, :job_property => valid_attributes
        response.should redirect_to(JobProperty.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved job_property as @job_property" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobProperty.any_instance.stub(:save).and_return(false)
        post :create, :job_property => {}
        assigns(:job_property).should be_a_new(JobProperty)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        JobProperty.any_instance.stub(:save).and_return(false)
        post :create, :job_property => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested job_property" do
        job_property = JobProperty.create! valid_attributes
        # Assuming there are no other job_properties in the database, this
        # specifies that the JobProperty created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        JobProperty.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => job_property.id, :job_property => {'these' => 'params'}
      end

      it "assigns the requested job_property as @job_property" do
        job_property = JobProperty.create! valid_attributes
        put :update, :id => job_property.id, :job_property => valid_attributes
        assigns(:job_property).should eq(job_property)
      end

      it "redirects to the job_property" do
        job_property = JobProperty.create! valid_attributes
        put :update, :id => job_property.id, :job_property => valid_attributes
        response.should redirect_to(job_property)
      end
    end

    describe "with invalid params" do
      it "assigns the job_property as @job_property" do
        job_property = JobProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobProperty.any_instance.stub(:save).and_return(false)
        put :update, :id => job_property.id.to_s, :job_property => {}
        assigns(:job_property).should eq(job_property)
      end

      it "re-renders the 'edit' template" do
        job_property = JobProperty.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        JobProperty.any_instance.stub(:save).and_return(false)
        put :update, :id => job_property.id.to_s, :job_property => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested job_property" do
      job_property = JobProperty.create! valid_attributes
      expect {
        delete :destroy, :id => job_property.id.to_s
      }.to change(JobProperty, :count).by(-1)
    end

    it "redirects to the job_properties list" do
      job_property = JobProperty.create! valid_attributes
      delete :destroy, :id => job_property.id.to_s
      response.should redirect_to(job_properties_url)
    end
  end

end
